# global:
#   scrape_interval: 15s
#   scrape_timeout: 10s
#   evaluation_interval: 15s
# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets: []
# scrape_configs:
# - job_name: prometheus
#   honor_timestamps: true
#   metrics_path: /metrics
#   scheme: http
#   static_configs:
#   - targets:
#     - prometheus:9090
# - job_name: docker_daemon
#   metrics_path: /metrics
#   static_configs:
#   - targets:
#     - 13.232.172.27:9323

global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "prometheus:9090"

  - job_name: "docker_daemon"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "65.2.146.8:9323"
